version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
    # environment:
    #   - CASSANDRA_CLUSTER_NAME=citizix

volumes:
  cassandra: